services:
  postgres:
    image: postgis/postgis:16-3.4-alpine
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=ThisPasswordIsOnlyUsedForDev
      - POSTGRES_DB=travel-planner-local
  nginx:
    image: nginx:1.25.4-alpine
    volumes:
      - "./nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro"
      - "./nginx/frontend:/usr/share/nginx/html:ro"
    network_mode: host
  geoserver:
    image: docker.osgeo.org/geoserver:2.25.0
    ports:
      - "127.0.0.1:8085:8080"
    environment:
      - SKIP_DEMO_DATA=true
      - INSTALL_EXTENSIONS=true
      - STABLE_EXTENSIONS=netcdf
      - EXTRA_JAVA_OPTS=-Xmx2g -DNETCDF_DATA_DIR=/opt/netcdf_cache
    volumes:
      - ./geoserver/additional_libs:/opt/additional_libs
      - ./geoserver/data:/opt/geoserver_data
      - ./geoserver/workspaces:/opt/geoserver_data/workspaces
      - ./geoserver/gwc-layers:/opt/geoserver_data/gwc-layers
      - ./geoserver/ndfd-nc:/opt/geoserver_data/ndfd-nc:ro
      - ./geoserver/netcdf_cache:/opt/netcdf_cache
