version: '3.1'

services:
  postgres:
    image: postgis/postgis:16-3.4-alpine
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=ThisPasswordIsOnlyUsedForDev
      - POSTGRES_DB=travel-planner-local